language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
      env: DEPENDENCIES=low
    - php: 5.4
      env: DEPENDENCIES=low

before_script:
  - composer self-update
  - if [ $DEPENDENCIES = low ] ; then composer update --prefer-dist --prefer-lowest --prefer-stable ; fi
  - if [ ! $DEPENDENCIES ] ; then composer update --prefer-dist ; fi
  - composer install

script:
  - ./vendor/bin/phpcbf --standard=PSR2 -v src/
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
